# Generated by Django 6.0.6 on 2026-07-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_address_order_delivery_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cart',
            field=models.BooleanField(default=False),
        ),
    ]
