# Generated by Django 6.0.6 on 2026-06-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('non-alcohol', 'Non-Alcoholic'), ('fermented', 'Fermented'), ('distilled', 'Distilled')], max_length=20)),
                ('subcategory', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.CharField(max_length=20)),
                ('abv', models.CharField(choices=[('none', 'Non-Alcoholic (0%)'), ('low', 'Low (under 8%)'), ('medium', 'Medium (8-20%)'), ('high', 'High (20%+)')], max_length=10)),
                ('emoji', models.CharField(max_length=8)),
                ('tags', models.JSONField(default=list)),
            ],
        ),
    ]
