# Generated by Django 6.0.6 on 2026-07-04 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('non-alcohol', 'Non-Alcoholic'), ('fermented', 'Fermented'), ('distilled', 'Distilled')], max_length=20)),
                ('subcategory', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.PositiveIntegerField(help_text='Volume in millilitres')),
                ('abv', models.DecimalField(decimal_places=1, help_text='Alcohol by volume, %', max_digits=4)),
                ('emoji', models.CharField(max_length=8)),
                ('tags', models.JSONField(default=list)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
