# Generated by Django 6.0.6 on 2026-07-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('non-alcohol', 'Non-Alcoholic'), ('fermented', 'Fermented'), ('distilled', 'Distilled'), ('cocktail', 'Cocktail Ingredients'), ('ice', 'Ice'), ('dairy', 'Dairy Products'), ('fresh', 'Fresh Products'), ('disposable', 'Disposable Products'), ('snacks', 'Bar Snacks')], max_length=20),
        ),
    ]
