# Generated by Django 6.0.6 on 2026-07-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='emoji',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, default='', help_text='File name inside static/images/, e.g. soft_drinks.jpg', max_length=100),
        ),
    ]
