# Generated by Django 6.0.6 on 2026-07-14 19:29

import django.core.validators
from django.db import migrations, models


def lowercase_emails(apps, schema_editor):
    """Tidy any address already stored with capitals.

    The unique check on email is case-sensitive, so before this change
    'Test@Bar.com' and 'test@bar.com' could both exist as separate accounts.
    Storing every address lowercase is what makes that constraint do its job.

    If two rows differ only by case, the one already holding the lowercase
    address is left alone and the other is skipped rather than being merged or
    deleted: which account is the real one is a decision for a person, not for a
    migration.
    """
    Users = apps.get_model('accounts', 'Users')
    for user in Users.objects.order_by('id'):
        tidy = (user.email or '').strip().lower()
        if tidy == user.email:
            continue
        if Users.objects.filter(email=tidy).exclude(pk=user.pk).exists():
            continue          # would collide: leave it for a human to sort out
        user.email = tidy
        user.save(update_fields=['email'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_users_full_name_users_first_name_and_more'),
    ]

    operations = [
        migrations.RunPython(lowercase_emails, noop),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Please use letters only. A name may include spaces, hyphens (-) and apostrophes ('), but not numbers or symbols.", regex="^[^\\W\\d_]+(?:[ '\\-.][^\\W\\d_]+)*$")]),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Please use letters only. A name may include spaces, hyphens (-) and apostrophes ('), but not numbers or symbols.", regex="^[^\\W\\d_]+(?:[ '\\-.][^\\W\\d_]+)*$")]),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number with at least 8 digits, e.g. +30 6900 111111.', regex='^\\+?(?=(?:\\D*\\d){8,})[\\d \\(\\)\\-]{8,20}$')]),
        ),
    ]
